spring:
  application:
    name: mmpay-app
  flyway:
    locations: classpath:db/migration/iam,classpath:db/migration/gateway,classpath:db/migration/audit
  datasource:
    hikari:
      connection-init-sql: SET ROLE mmpay_app_role

management:
  endpoints:
    web:
      exposure:
        include: health,info,env,configprops,metrics
  endpoint:
    health:
      probes:
        enabled: true
    info:
      enabled: true
