CREATE TABLE audit_event (
  id BIGINT PRIMARY KEY,
  ts TIMESTAMP NOT NULL,
  actor_kind VARCHAR(32) NOT NULL,
  actor_id VARCHAR(128) NOT NULL,
  action VARCHAR(128) NOT NULL,
  target_kind VARCHAR(64) NOT NULL,
  target_id VARCHAR(128) NOT NULL,
  details_json VARCHAR(4000) NOT NULL,
  prev_row_hmac VARCHAR(128),
  row_hmac VARCHAR(128) NOT NULL,
  tenant_id VARCHAR(64) NOT NULL DEFAULT 'default',
  chain_anchor BOOLEAN NOT NULL DEFAULT FALSE
);
CREATE SEQUENCE audit_event_id_seq START WITH 1 INCREMENT BY 1;

CREATE TABLE webhook_integrations (
  id VARCHAR(64) PRIMARY KEY,
  display_name VARCHAR(128) NOT NULL,
  target_url VARCHAR(512) NOT NULL,
  secret_ref VARCHAR(256) NOT NULL,
  secret_fingerprint VARCHAR(64) NOT NULL,
  legacy_header_alias BOOLEAN NOT NULL DEFAULT false,
  legacy_module_required BOOLEAN NOT NULL DEFAULT false,
  status VARCHAR(16) NOT NULL DEFAULT 'active',
  kind VARCHAR(16) NOT NULL DEFAULT 'webhook',
  slug VARCHAR(64) NOT NULL UNIQUE,
  relay_target_id VARCHAR(64),
  tenant_id VARCHAR(64) NOT NULL DEFAULT 'default',
  created_at TIMESTAMP NOT NULL,
  updated_at TIMESTAMP NOT NULL
);

CREATE TABLE license_relay_targets (
  id VARCHAR(64) PRIMARY KEY,
  display_name VARCHAR(128) NOT NULL,
  target_url VARCHAR(512) NOT NULL,
  status VARCHAR(16) NOT NULL,
  tenant_id VARCHAR(64) NOT NULL DEFAULT 'default',
  created_at TIMESTAMP NOT NULL,
  updated_at TIMESTAMP NOT NULL,
  version BIGINT NOT NULL DEFAULT 0
);

CREATE TABLE license_relay_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  target_id VARCHAR(64) NOT NULL,
  request_id VARCHAR(64) NOT NULL,
  attempt SMALLINT NOT NULL,
  byte_count INTEGER NOT NULL,
  payload_sha256 CHAR(64) NOT NULL,
  http_status SMALLINT,
  response_sha256 CHAR(64),
  response_size_bytes INTEGER,
  response_truncated BOOLEAN NOT NULL DEFAULT false,
  error_class VARCHAR(64),
  synthetic BOOLEAN NOT NULL DEFAULT false,
  vendor_cert_issuer_dn_sha256 CHAR(64),
  vendor_cert_serial VARCHAR(64),
  dead_letter BOOLEAN NOT NULL DEFAULT false,
  dispatched_at TIMESTAMP NOT NULL,
  tenant_id VARCHAR(64) NOT NULL DEFAULT 'default'
);
