DROP TABLE IF EXISTS delivery_logs;
DROP TABLE IF EXISTS webhook_integrations;
DROP TABLE IF EXISTS reconciliation_runs;
DROP TABLE IF EXISTS provider_events;
DROP TABLE IF EXISTS refunds;
DROP TABLE IF EXISTS transactions;
DROP TABLE IF EXISTS payment_intents;
DROP TABLE IF EXISTS channels;
DROP TABLE IF EXISTS merchants;

CREATE TABLE merchants (
  row_uid VARCHAR(36) PRIMARY KEY,
  id VARCHAR(64) NOT NULL,
  display_name VARCHAR(128) NOT NULL,
  credential_handle VARCHAR(256) NOT NULL,
  credential_ref VARCHAR(256),
  credential_fingerprint VARCHAR(8),
  status VARCHAR(16) NOT NULL,
  tenant_id VARCHAR(64) NOT NULL,
  created_at TIMESTAMP NOT NULL,
  updated_at TIMESTAMP NOT NULL
);

CREATE UNIQUE INDEX merchants_id_active_uniq
  ON merchants (id, status);

CREATE TABLE channels (
  row_uid VARCHAR(36) PRIMARY KEY,
  id VARCHAR(64) NOT NULL,
  merchant_id VARCHAR(64) NOT NULL,
  display_name VARCHAR(128),
  provider_code VARCHAR(64) NOT NULL,
  credential_handle VARCHAR(256) NOT NULL,
  credential_ref VARCHAR(256),
  credential_fingerprint VARCHAR(8),
  status VARCHAR(16) NOT NULL,
  tenant_id VARCHAR(64) NOT NULL,
  created_at TIMESTAMP NOT NULL,
  updated_at TIMESTAMP NOT NULL
);

CREATE UNIQUE INDEX channels_id_active_uniq
  ON channels (id, status);

CREATE TABLE payment_intents (
  id VARCHAR(64) PRIMARY KEY,
  merchant_id VARCHAR(64) NOT NULL,
  channel_id VARCHAR(64) NOT NULL,
  provider_order_id VARCHAR(128),
  amount_minor BIGINT NOT NULL,
  currency VARCHAR(8) NOT NULL,
  order_ref VARCHAR(128) NOT NULL,
  idempotency_key VARCHAR(128) NOT NULL UNIQUE,
  status VARCHAR(32) NOT NULL,
  tenant_id VARCHAR(64) NOT NULL,
  created_at TIMESTAMP NOT NULL,
  updated_at TIMESTAMP NOT NULL,
  version BIGINT NOT NULL DEFAULT 0
);

CREATE TABLE transactions (
  id VARCHAR(64) PRIMARY KEY,
  payment_intent_id VARCHAR(64) NOT NULL,
  provider_event_id VARCHAR(128),
  amount_minor BIGINT NOT NULL,
  currency VARCHAR(8) NOT NULL,
  status VARCHAR(32) NOT NULL,
  tenant_id VARCHAR(64) NOT NULL,
  created_at TIMESTAMP NOT NULL
);

CREATE TABLE refunds (
  id VARCHAR(64) PRIMARY KEY,
  transaction_id VARCHAR(64),
  payment_intent_id VARCHAR(64) NOT NULL,
  merchant_id VARCHAR(64) NOT NULL,
  amount_minor BIGINT NOT NULL,
  currency VARCHAR(8) NOT NULL,
  status VARCHAR(32) NOT NULL,
  tenant_id VARCHAR(64) NOT NULL,
  requested_at TIMESTAMP NOT NULL,
  version BIGINT NOT NULL DEFAULT 0
);

CREATE TABLE provider_events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  provider_code VARCHAR(32) NOT NULL,
  provider_event_id VARCHAR(128) NOT NULL,
  payment_intent_id VARCHAR(64),
  raw_signature_sha256 CHAR(64) NOT NULL,
  accepted_at TIMESTAMP NOT NULL,
  duplicate_count INT NOT NULL DEFAULT 0,
  tenant_id VARCHAR(64) NOT NULL,
  UNIQUE (provider_code, provider_event_id)
);

CREATE TABLE webhook_integrations (
  id VARCHAR(64) PRIMARY KEY,
  display_name VARCHAR(128) NOT NULL,
  target_url VARCHAR(2048) NOT NULL,
  secret_ref VARCHAR(256) NOT NULL,
  secret_fingerprint CHAR(8) NOT NULL,
  legacy_header_alias VARCHAR(128),
  legacy_module_required BOOLEAN NOT NULL DEFAULT FALSE,
  status VARCHAR(16) NOT NULL,
  tenant_id VARCHAR(64) NOT NULL,
  created_at TIMESTAMP NOT NULL,
  updated_at TIMESTAMP NOT NULL
);

CREATE TABLE delivery_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  integration_id VARCHAR(64) NOT NULL,
  payment_intent_id VARCHAR(64) NOT NULL,
  event_id VARCHAR(36) NOT NULL,
  attempt INT NOT NULL,
  scheduled_at TIMESTAMP NOT NULL,
  dispatched_at TIMESTAMP,
  response_status INT,
  response_body_sha256 CHAR(64),
  next_retry_at TIMESTAMP,
  dead_letter BOOLEAN NOT NULL DEFAULT FALSE,
  bulk_redispatch_batch_id VARCHAR(36),
  tenant_id VARCHAR(64) NOT NULL
);

CREATE TABLE reconciliation_runs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  run_date DATE NOT NULL,
  provider_code VARCHAR(32) NOT NULL,
  channel_id VARCHAR(64) NOT NULL,
  ingest_count BIGINT NOT NULL,
  matched_count BIGINT NOT NULL,
  unmatched_count BIGINT NOT NULL,
  outcome VARCHAR(16) NOT NULL,
  ack_status VARCHAR(16) NOT NULL,
  ack_at TIMESTAMP,
  ack_actor VARCHAR(64),
  tenant_id VARCHAR(64) NOT NULL
);
