/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router

import type { GeneratedRoute } from '@elegant-router/types';

export const generatedRoutes: GeneratedRoute[] = [
  {
    name: '403',
    path: '/403',
    component: 'layout.blank$view.403',
    meta: {
      title: '403',
      i18nKey: 'route.403',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '404',
    path: '/404',
    component: 'layout.blank$view.404',
    meta: {
      title: '404',
      i18nKey: 'route.404',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '500',
    path: '/500',
    component: 'layout.blank$view.500',
    meta: {
      title: '500',
      i18nKey: 'route.500',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'home',
    path: '/home',
    component: 'layout.base$view.home',
    meta: {
      title: 'home',
      i18nKey: 'route.home',
      constant: true,
      icon: 'mdi:monitor-dashboard',
      order: 1
    }
  },
  {
    name: 'merchants',
    path: '/merchants',
    component: 'layout.base$view.merchants',
    meta: {
      title: 'merchants',
      i18nKey: 'route.merchants',
      constant: true,
      icon: 'mdi:store-cog',
      order: 2
    }
  },
  {
    name: 'merchant-detail',
    path: '/merchants/:id',
    component: 'layout.base$view.merchant-detail',
    props: true,
    meta: {
      title: 'merchant-detail',
      i18nKey: 'route.merchant-detail',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'merchant-channel-new',
    path: '/merchants/:id/channels/new',
    component: 'layout.base$view.merchant-channel-new',
    props: true,
    meta: {
      title: 'merchant-channel-new',
      i18nKey: 'route.merchant-channel-new',
      constant: true,
      hideInMenu: true,
      roles: ['ADMIN', 'admin', 'R_ADMIN']
    }
  },
  {
    name: 'channel-detail',
    path: '/channels/:id',
    component: 'layout.base$view.channel-detail',
    props: true,
    meta: {
      title: 'channel-detail',
      i18nKey: 'route.channel-detail',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'iframe-page',
    path: '/iframe-page/:url',
    component: 'layout.base$view.iframe-page',
    props: true,
    meta: {
      title: 'iframe-page',
      i18nKey: 'route.iframe-page',
      constant: true,
      hideInMenu: true,
      keepAlive: true
    }
  },
  {
    name: 'login',
    path: '/login/:module(pwd-login|code-login|register|reset-pwd|bind-wechat)?',
    component: 'layout.blank$view.login',
    props: true,
    meta: {
      title: 'login',
      i18nKey: 'route.login',
      constant: true,
      hideInMenu: true
    }
  }
];
