#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

usage() {
  cat <<EOF >&2
Usage: $0 <drill.json> <operator-ed25519-private-pem> <operator-pgp-fingerprint>

Reads canonical drill JSON, produces an Ed25519 signature with the operator's
evidence private key and a PGP detached signature with the operator's primary
key, then assembles the final docs/release/backup-restore-drill-evidence.md.

The PGP key must already be in the gpg agent or the GNUPGHOME env var, and its
fingerprint must match the one pinned in governance/operator-keys.yaml.
EOF
  exit 2
}

if [[ $# -ne 3 ]]; then
  usage
fi

CANONICAL_FILE="$1"
ED25519_PRIVATE_KEY="$2"
PGP_FINGERPRINT="$3"

[[ -f "$CANONICAL_FILE" ]] || { echo "canonical file missing: $CANONICAL_FILE" >&2; exit 1; }
[[ -f "$ED25519_PRIVATE_KEY" ]] || { echo "ed25519 private key missing: $ED25519_PRIVATE_KEY" >&2; exit 1; }

EVIDENCE_FILE="$ROOT_DIR/docs/release/backup-restore-drill-evidence.md"
TMP_SIG="$(mktemp)"
TMP_PGP="$(mktemp)"
trap 'rm -f "$TMP_SIG" "$TMP_PGP"' EXIT

openssl pkeyutl -sign -inkey "$ED25519_PRIVATE_KEY" -rawin -in "$CANONICAL_FILE" -out "$TMP_SIG"
ed25519_b64=$(base64 -w0 "$TMP_SIG")

gpg --batch --yes --local-user "$PGP_FINGERPRINT" --armor --detach-sign --output "$TMP_PGP" "$CANONICAL_FILE"
pgp_armor=$(cat "$TMP_PGP")

canonical_payload=$(cat "$CANONICAL_FILE")

cat > "$EVIDENCE_FILE" <<EOF
# MMPay Backup-Restore Drill Evidence

Evidence status: completed-external-evidence

The canonical drill payload below was generated by
\`scripts/run-backup-restore-drill.sh\` after a real \`pg_dump\`/restore loop
against the MMPay Postgres instance. It is signed twice: an Ed25519 signature by
the operator's evidence-signing key and a PGP detached signature by the operator
primary key pinned in \`governance/operator-keys.yaml\`.

-----BEGIN MMPAY BACKUP RESTORE DRILL-----
$canonical_payload
-----END MMPAY BACKUP RESTORE DRILL-----

-----BEGIN MMPAY DRILL ED25519 SIGNATURE-----
$ed25519_b64
-----END MMPAY DRILL ED25519 SIGNATURE-----

$pgp_armor
EOF

echo "Wrote $EVIDENCE_FILE"
